/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    'BradleyStrategyGroup-WebsiteContent-prod': {
      name: string;
      type: 'sst.aws.Bucket';
    };
    'BradleyStrategyGroup-prod': {
      type: 'sst.aws.Astro';
      url: string;
    };
    'deployTrigger-prod': {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
