// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Primary content in *Homepage → Slice zone → ServiceGrid → Primary*
 */
export interface HomepageDocumentDataBodyServicegridSlicePrimary {
	/**
	 * header field in *Homepage → Slice zone → ServiceGrid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].servicegrid.primary.header1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	header1: prismic.RichTextField;
	
	/**
	 * description field in *Homepage → Slice zone → ServiceGrid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].servicegrid.primary.description1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description1: prismic.RichTextField;
	
	/**
	 * background field in *Homepage → Slice zone → ServiceGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: white
	 * - **API ID Path**: homepage.body[].servicegrid.primary.background
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	background: prismic.SelectField<"white" | "black" | "green" | "blue" | "orange", "filled">;
}

/**
 * Item content in *Homepage → Slice zone → ServiceGrid → Items*
 */
export interface HomepageDocumentDataBodyServicegridSliceItem {
	/**
	 * title field in *Homepage → Slice zone → ServiceGrid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].servicegrid.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * body field in *Homepage → Slice zone → ServiceGrid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].servicegrid.items.body1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body1: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyServicegridSlice = prismic.Slice<"servicegrid", Simplify<HomepageDocumentDataBodyServicegridSlicePrimary>, Simplify<HomepageDocumentDataBodyServicegridSliceItem>>

/**
 * Primary content in *Homepage → Slice zone → Text Block → Primary*
 */
export interface HomepageDocumentDataBodyTextBlockSlicePrimary {
	/**
	 * header field in *Homepage → Slice zone → Text Block → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].text_block.primary.header1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	header1: prismic.RichTextField;
	
	/**
	 * body field in *Homepage → Slice zone → Text Block → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].text_block.primary.body1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body1: prismic.RichTextField;
	
	/**
	 * border field in *Homepage → Slice zone → Text Block → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: homepage.body[].text_block.primary.border
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	border: prismic.BooleanField;
	
	/**
	 * background field in *Homepage → Slice zone → Text Block → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: white
	 * - **API ID Path**: homepage.body[].text_block.primary.background
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	background: prismic.SelectField<"white" | "black" | "green" | "blue" | "orange", "filled">;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyTextBlockSlice = prismic.Slice<"text_block", Simplify<HomepageDocumentDataBodyTextBlockSlicePrimary>, never>

/**
 * Primary content in *Homepage → Slice zone → List Grid → Primary*
 */
export interface HomepageDocumentDataBodyListGridSlicePrimary {
	/**
	 * header field in *Homepage → Slice zone → List Grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].list_grid.primary.header1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	header1: prismic.RichTextField;
	
	/**
	 * description field in *Homepage → Slice zone → List Grid → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].list_grid.primary.description1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description1: prismic.RichTextField;
	
	/**
	 * background field in *Homepage → Slice zone → List Grid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: white
	 * - **API ID Path**: homepage.body[].list_grid.primary.background
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	background: prismic.SelectField<"white" | "black" | "green" | "blue" | "orange", "filled">;
}

/**
 * Item content in *Homepage → Slice zone → List Grid → Items*
 */
export interface HomepageDocumentDataBodyListGridSliceItem {
	/**
	 * title field in *Homepage → Slice zone → List Grid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].list_grid.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * list field in *Homepage → Slice zone → List Grid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].list_grid.items.list
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	list: prismic.RichTextField;
	
	/**
	 * bullet field in *Homepage → Slice zone → List Grid → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: default
	 * - **API ID Path**: homepage.body[].list_grid.items.bullet
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	bullet: prismic.SelectField<"default" | "circle" | "square" | "diamond" | "triangle", "filled">;
	
	/**
	 * link field in *Homepage → Slice zone → List Grid → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].list_grid.items.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyListGridSlice = prismic.Slice<"list_grid", Simplify<HomepageDocumentDataBodyListGridSlicePrimary>, Simplify<HomepageDocumentDataBodyListGridSliceItem>>

/**
 * Primary content in *Homepage → Slice zone → Line → Primary*
 */
export interface HomepageDocumentDataBodyLineSlicePrimary {
	/**
	 * colour field in *Homepage → Slice zone → Line → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: black
	 * - **API ID Path**: homepage.body[].line.primary.colour
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	colour: prismic.SelectField<"black" | "green" | "blue" | "orange", "filled">;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyLineSlice = prismic.Slice<"line", Simplify<HomepageDocumentDataBodyLineSlicePrimary>, never>

/**
 * Primary content in *Homepage → Slice zone → ContactForm → Primary*
 */
export interface HomepageDocumentDataBodyContactformSlicePrimary {
	/**
	 * title field in *Homepage → Slice zone → ContactForm → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].contactform.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * body field in *Homepage → Slice zone → ContactForm → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].contactform.primary.body1
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body1: prismic.RichTextField;
	
	/**
	 * Email Name field in *Homepage → Slice zone → ContactForm → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].contactform.primary.email_name
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	email_name: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyContactformSlice = prismic.Slice<"contactform", Simplify<HomepageDocumentDataBodyContactformSlicePrimary>, never>

type HomepageDocumentDataBodySlice = HomepageDocumentDataBodyServicegridSlice | HomepageDocumentDataBodyTextBlockSlice | HomepageDocumentDataBodyListGridSlice | HomepageDocumentDataBodyLineSlice | HomepageDocumentDataBodyContactformSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * header field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.header
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	header: prismic.RichTextField;
	
	/**
	 * tagline field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.tagline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	tagline: prismic.RichTextField;
	
	/**
	 * description field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Slice zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<HomepageDocumentDataBodySlice>;/**
	 * og_title field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	og_title: prismic.RichTextField;
	
	/**
	 * og_description field in *Homepage*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	og_description: prismic.RichTextField;
	
	/**
	 * og_image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

export type AllDocumentTypes = HomepageDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataBodyServicegridSlicePrimary,
			HomepageDocumentDataBodyServicegridSliceItem,
			HomepageDocumentDataBodyTextBlockSlicePrimary,
			HomepageDocumentDataBodyListGridSlicePrimary,
			HomepageDocumentDataBodyListGridSliceItem,
			HomepageDocumentDataBodyLineSlicePrimary,
			HomepageDocumentDataBodyContactformSlicePrimary,
			HomepageDocumentDataBodySlice,
			AllDocumentTypes
		}
	}
}