name: deploy.yml
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ trigger-from-lambda ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Set Production account variables
        run: |
          echo "AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }}" >> $GITHUB_ENV
          echo "STAGE=prod" >> $GITHUB_ENV
          echo "PRISMIC_CUSTOM_TYPES_API_TOKEN=${{ secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN }}" >> $GITHUB_ENV
          echo "PUBLIC_PRISMIC_ACCESS_TOKEN=${{ secrets.PUBLIC_PRISMIC_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "PUBLIC_PRISMIC_REPO_NAME=${{ secrets.PUBLIC_PRISMIC_REPO_NAME }}" >> $GITHUB_ENV
          echo "PRISMIC_API_ENDPOINT=${{ secrets.PRISMIC_API_ENDPOINT }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-build-agent
          aws-region: eu-west-2

      - name: Set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Build app
        run: yarn install

      - name: Deploy app
        run: yarn deploy:prod
